# Generated by Django 5.2.6 on 2026-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='org_unit_id',
            field=models.IntegerField(default=-1),
        ),
    ]
