# Generated by Django 5.2.6 on 2026-08-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_building_org_unit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='org_unit_id',
            new_name='orgunit_id',
        ),
    ]
