# Generated by Django 5.2.6 on 2026-08-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='floors',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floors', to='organization.building'),
        ),
    ]
