# Generated by Django 5.2.6 on 2026-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_rename_floors_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
