# Generated by Django 6.1 on 2026-08-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_roomcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=500, upload_to='room-categories/'),
        ),
    ]
